### PR TITLE
Check for existence of fields before setting in profile

### PR DESCRIPTION
**Pull request by adamreisnz**
To make consistent with the other oAuth passport libs

### CODE REVIEW

**Comment by rwky** [comment]
Not too keen on this one, this can break existing code.
If someone pulls a profile which has no name fields then `profile.name` won't exist so if someone is checking for `profile.name.givenName` they will get `TypeError: Cannot read property 'givenName' of undefined` instead of simply a value of `undefined`.

**Comment by adamreisnz** [comment]
In that case, we should probably update the other strategies to match, because the google oauth 2 strategy does the same thing.

If the goal is for these strategies to return semi-consistent profiles, them we should probably strive to make them behave consistently.

And I do think we can put in the checks for the other fields (e.g. birthday, gender), to avoid an empty profile with a lot of undefined values.

**Comment by rwky** [comment]
Ugh you're right about the google oauth 2. I'll raise an issue in the main passport repo for this and have a think.

**Comment by rwky** [comment]
https://github.com/passport-next/passport/issues/16 made the issue for discussion.

**Pull request closed without merging**
